version: '3.6'

services:
  mysql:
    container_name: td-db
    image: mysql:5.7
    restart: always
    volumes:
      - ./volumes/database:/var/lib/mysql
    environment: # Warning : environment parameters will be ignored if volume already exists (delete td-db if needed + run docker-compose rm -fv)
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=td
      - MYSQL_USER=julien
      - MYSQL_PASSWORD=password
#    ports:
#      - 3306:3306
  
  migrations: 
    container_name: td-migrations
    image: td-sql-migrations:latest
    depends_on: 
      - mysql
    environment:
      - WAIT_HOST=td-db
      - WAIT_PORT=3306

  api:
    container_name: td-api
    image: td-api:latest
    restart: always
    depends_on:
      - mysql
      - migrations
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - WAIT_HOST=td-db
      - WAIT_PORT=3306

  nginx:
    container_name: td-nginx
    image: nginx
    volumes:
#      - ./nginx.nohttps.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt/www:/usr/share/nginx/html
      - /var/local/dhparam.pem:/etc/ssl/certs/dhparam-2048.pem
      - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
      - static
    ports:
      - 80:80
      - 443:443

